# Generated by Django 5.1.2 on 2025-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default', upload_to='images/'),
            preserve_default=False,
        ),
    ]
