# Generated by Django 5.1.2 on 2025-04-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_item_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
