# Generated by Django 5.1.2 on 2025-08-09 09:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_item_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), blank=True, default=list, size=None),
        ),
    ]
