# Generated by Django 4.2.23 on 2025-08-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_item_price_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_history',
        ),
    ]
