# Generated by Django 4.2.23 on 2025-09-09 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_item_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
