# Generated by Django 4.2.23 on 2025-09-16 09:30

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_item_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available_duration',
        ),
        migrations.AddField(
            model_name='item',
            name='expires_at',
            field=models.DateTimeField(default=auction.models.Item.default_expiry),
        ),
    ]
