# Generated by Django 4.2.25 on 2026-01-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_bidhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='auction.item'),
        ),
    ]
