# Generated by Django 4.2.28 on 2026-02-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_item_created_at 2'),
        ('auction', '0009_remove_item_available_duration_item_expires_at 2'),
        ('auction', '0010_bidhistory 2'),
        ('auction', '0011_bidhistory_price_alter_bidhistory_history'),
    ]

    operations = [
    ]
